### ISSUE TITLE
Integrate new_since_timestamp Galois API

### ISSUE THREAD

**Issue by BeckySharp** [clulab/ConceptAlignment#19]

**Comment by kwalcock** [comment]
I have accounted for this to some extent in our code, but the functionality doesn't seem to be ready in SuperMaaS.  I filed an issue.

**Comment by kwalcock** [comment]
It does appear possible to increment an index with hnswlib (https://github.com/jelmerk/hnswlib).  There's a parameter for the maximum size, which would probably need to change from the actual size to something larger.  ISI has some information about modification dates (https://datamart-upload.readthedocs.io/en/latest/#describing-dataset-metadata) which could be used to avoid checking for variables that shouldn't have changed.  Lots of metadata is optional, including the modification date.  It is not possible to filter so as not to even see old data.  We've pretty much agreed that this is a wish list item, at least until larger amounts of data are used so that this is necessary.  Until then, there are many more important issues.
