### ISSUE TITLE
API endpoint to trigger re-index of metadata

### ISSUE THREAD

**Issue by BeckySharp** [clulab/ConceptAlignment#21]

**Comment by kwalcock** [comment]
Right now I don't think this will be done via API.  This is a privileged operation that not just anyone should be allowed to do and it seems premature to add authentication/authorization.  If a cron job, either by timer or manual intervention, is responsible for the reindexing, then it can also restart the server or otherwise signal it to display new data.

**Comment by kwalcock** [comment]
This is now done via API but with the inclusion of a password/secret than can be set when the webapp starts.
